### ISSUE TITLE
Positional attention

### ISSUE THREAD

**Issue by markobogoevski** [gautierdag/pytorch-attentive-lm#1]
Hello, just wanna ask which paper is the positional attention layer from?

**Comment by gautierdag** [comment]
It's from this paper that we published at ACL 2020: `[Location Attention for Extrapolation to Longer Sequences](https://aclanthology.org/2020.acl-main.39.pdf)`, see section 4.2.. 

It's a bare bones implementation of the positional attention we propose in the paper. Unfortunately, as you can see from results in the README it did not outperform the _Merity et al_ RNN baseline (which is unreasonably good 😅) and this experimentation was not included in the final draft.
